<?php

// WordPress title tag management
add_theme_support('title-tag');

// ########## MENUS ##########

// Enable menus feature
add_theme_support('menus');

// Define menus locations
register_nav_menus([
    'main-menu'  => 'Main navigation',
    'footer-menu'     => 'Footer navigation'
]);

// ########## ACF ##########

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6687b087ccd88',
	'title' => 'Accueil',
	'fields' => array(
		array(
			'key' => 'field_6687b106dd687',
			'label' => 'Titre sur la bannière',
			'name' => 'home__header_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Murmures à la Lune',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6687b86e79590',
			'label' => 'Sous-titre sur la bannière',
			'name' => 'home__header_subtitle',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6687b089dd686',
			'label' => 'Image de bannière',
			'name' => 'home__header_wallpaper',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_668f9073a8465',
			'label' => 'Titre de la section parutions',
			'name' => 'home__books_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Nos dernières parutions',
			'maxlength' => '',
			'placeholder' => 'Nos dernières parutions :',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6687c34c9df16',
			'label' => 'Nos parutions',
			'name' => 'home__books',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6687c3a19df17',
					'label' => 'Titre de l\'ouvrage',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6687c34c9df16',
				),
				array(
					'key' => 'field_6687c3bb9df18',
					'label' => 'Auteur',
					'name' => 'author',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6687c34c9df16',
				),
				array(
					'key' => 'field_6687c3cb9df19',
					'label' => 'Couverture',
					'name' => 'cover',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_6687c34c9df16',
				),
				array(
					'key' => 'field_668fa6f8cb014',
					'label' => 'Permalien',
					'name' => 'permalink',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'http://murmures-lune.local/livre/',
					'placeholder' => '',
					'parent_repeater' => 'field_6687c34c9df16',
				),
			),
		),
		array(
			'key' => 'field_668f9d05e3e3d',
			'label' => 'Les derniers articles',
			'name' => 'home__articles_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Les derniers articles',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6690eb8adb67c',
	'title' => 'Articles',
	'fields' => array(
		array(
			'key' => 'field_6690ebc1532f1',
			'label' => 'Texte de l\'article',
			'name' => 'post__text',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6690f21d80408',
			'label' => 'Date de début de l\'événement',
			'name' => 'post__date',
			'aria-label' => '',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y H:i',
			'return_format' => 'd/m/Y H:i',
			'first_day' => 1,
		),
		array(
			'key' => 'field_6690f36bf6e1c',
			'label' => 'Date de fin de l\'événement',
			'name' => 'post__date_end',
			'aria-label' => '',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y H:i',
			'return_format' => 'd/m/Y H:i',
			'first_day' => 1,
		),
		array(
			'key' => 'field_6690ebdc532f2',
			'label' => 'Image de l\'article',
			'name' => 'post__image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6690f1dd80407',
			'label' => 'Galerie de l\'article',
			'name' => 'post__gallery',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'insert' => 'append',
			'preview_size' => 'medium',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_668fe5daab065',
	'title' => 'Liste des livres',
	'fields' => array(
		array(
			'key' => 'field_668fe5db7fa69',
			'label' => 'Titre de la page',
			'name' => 'books__title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_668fe7cc9988b',
			'label' => 'Paragraphe de présentation',
			'name' => 'books__description',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Voici tous nos livres parus',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_668fe64c7fa6a',
			'label' => 'Les cartes des livres',
			'name' => 'books__cards',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_668fe68b7fa6b',
					'label' => 'Titre',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_668fe64c7fa6a',
				),
				array(
					'key' => 'field_668fe69e7fa6c',
					'label' => 'Autrice',
					'name' => 'author',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_668fe64c7fa6a',
				),
				array(
					'key' => 'field_668fe6a87fa6d',
					'label' => 'Couverture',
					'name' => 'cover',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_668fe64c7fa6a',
				),
			),
		),
		array(
			'key' => 'field_668fe6ed72f67',
			'label' => 'Genres',
			'name' => 'books__genres',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'genre',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'archive-book.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6687eb3c22c40',
	'title' => 'Livre',
	'fields' => array(
		array(
			'key' => 'field_6687eb3d9e438',
			'label' => 'Titre',
			'name' => 'book__title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6687eb599e439',
			'label' => 'Autrice ou auteur',
			'name' => 'book__author',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6687eb799e43a',
			'label' => 'Couverture',
			'name' => 'book__cover',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6687eb899e43b',
			'label' => 'Date de parution',
			'name' => 'book__date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_6687ebbe9e43d',
			'label' => 'Extrait',
			'name' => 'book__extract',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6687ebe29e43e',
			'label' => 'Disponibilité',
			'name' => 'book__dispo',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'À paraître' => 'À paraître',
				'Disponible' => 'Disponible',
				'Réimpression en cours' => 'Réimpression en cours',
				'Épuisé' => 'Épuisé',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6687ebfb9e43f',
			'label' => 'Prix',
			'name' => 'book__price',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 0,
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '€',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'livre',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

// ######### CPT #########

function cptui_register_my_taxes_genre() {

	/**
	 * Taxonomy: Genres.
	 */

	$labels = [
		"name" => esc_html__( "Genres", "custom-post-type-ui" ),
		"singular_name" => esc_html__( "Genre", "custom-post-type-ui" ),
		"menu_name" => esc_html__( "Genres", "custom-post-type-ui" ),
		"all_items" => esc_html__( "Tous les Genres", "custom-post-type-ui" ),
		"edit_item" => esc_html__( "Éditer le Genre", "custom-post-type-ui" ),
		"view_item" => esc_html__( "Voir le Genre", "custom-post-type-ui" ),
		"update_item" => esc_html__( "Mettre à jour le nom du Genre", "custom-post-type-ui" ),
		"add_new_item" => esc_html__( "Ajouter un nouveau Genre", "custom-post-type-ui" ),
		"new_item_name" => esc_html__( "Nouveau nom de Genre", "custom-post-type-ui" ),
		"parent_item" => esc_html__( "Genre parent", "custom-post-type-ui" ),
		"parent_item_colon" => esc_html__( "Genre parent:", "custom-post-type-ui" ),
		"search_items" => esc_html__( "Chercher les Genres", "custom-post-type-ui" ),
		"popular_items" => esc_html__( "Genres populaires", "custom-post-type-ui" ),
		"separate_items_with_commas" => esc_html__( "Séparer les Genres par des virgules", "custom-post-type-ui" ),
		"add_or_remove_items" => esc_html__( "Ajouter ou retirer des Genres", "custom-post-type-ui" ),
		"choose_from_most_used" => esc_html__( "Choisir parmi les Genres les plus utilisés", "custom-post-type-ui" ),
		"not_found" => esc_html__( "Aucun Genre trouvé", "custom-post-type-ui" ),
		"no_terms" => esc_html__( "Pas de Genres", "custom-post-type-ui" ),
		"items_list_navigation" => esc_html__( "Navigation dans la liste des Genres", "custom-post-type-ui" ),
		"items_list" => esc_html__( "Liste des Genres", "custom-post-type-ui" ),
		"back_to_items" => esc_html__( "Revenir aux Genres", "custom-post-type-ui" ),
		"name_field_description" => esc_html__( "Le nom est tel qu'il apparaît sur votre site.", "custom-post-type-ui" ),
		"parent_field_description" => esc_html__( "Assignez un terme parent pour créer une hiérarchie. Par exemple, Jazz serait le parent de Cool-jazz ou Be-bop.", "custom-post-type-ui" ),
		"slug_field_description" => esc_html__( "Le slug est la version du nom qui convient à une URL. C'est en général en minuscule et ça ne contient que des lettres, chiffres et tirets (-).", "custom-post-type-ui" ),
		"desc_field_description" => esc_html__( "La description n'est pas visible par défaut ; cependant, certains thèmes peuvent la faire apparaître..", "custom-post-type-ui" ),
	];

	
	$args = [
		"label" => esc_html__( "Genres", "custom-post-type-ui" ),
		"labels" => $labels,
		"public" => true,
		"publicly_queryable" => true,
		"hierarchical" => true,
		"show_ui" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"query_var" => true,
		"rewrite" => [ 'slug' => 'genre', 'with_front' => true, ],
		"show_admin_column" => false,
		"show_in_rest" => true,
		"show_tagcloud" => false,
		"rest_base" => "genre",
		"rest_controller_class" => "WP_REST_Terms_Controller",
		"rest_namespace" => "wp/v2",
		"show_in_quick_edit" => false,
		"sort" => false,
		"show_in_graphql" => false,
	];
	register_taxonomy( "genre", [ "livre" ], $args );
}
add_action( 'init', 'cptui_register_my_taxes_genre' );